<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-M4Q3J59" failures="0" tests="1" name="DriverFactory.DriverScript" time="29.313" errors="1" timestamp="2022-09-17T07:40:22 BST" skipped="0">
  <testcase classname="DriverFactory.DriverScript" name="startTest" time="29.313">
    <error message="Cannot invoke &quot;org.apache.poi.xssf.usermodel.XSSFCell.getCellType()&quot; because the return value of &quot;org.apache.poi.xssf.usermodel.XSSFRow.getCell(int)&quot; is null" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: Cannot invoke "org.apache.poi.xssf.usermodel.XSSFCell.getCellType()" because the return value of "org.apache.poi.xssf.usermodel.XSSFRow.getCell(int)" is null
at Utilities.ExcelFileUtil.getcellData(ExcelFileUtil.java:38)
at DriverFactory.DriverScript.startTest(DriverScript.java:29)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </error>
  </testcase> <!-- startTest -->
  <system-out>
    <![CDATA[no.of rows:::9 no.of cells:::3
login success:::dashboard http://orangehrm.qedgetech.com/symfony/web/index.php/dashboard
Invalid credentials dashboard http://orangehrm.qedgetech.com/symfony/web/index.php/auth/validateCredentials
login success:::dashboard http://orangehrm.qedgetech.com/symfony/web/index.php/dashboard
login success:::dashboard http://orangehrm.qedgetech.com/symfony/web/index.php/dashboard
login success:::dashboard http://orangehrm.qedgetech.com/symfony/web/index.php/dashboard
Invalid credentials dashboard http://orangehrm.qedgetech.com/symfony/web/index.php/auth/validateCredentials
Invalid credentials dashboard http://orangehrm.qedgetech.com/symfony/web/index.php/auth/validateCredentials]]>
  </system-out>
</testsuite> <!-- DriverFactory.DriverScript -->
